{"name": "Tracking non-existent number returns client error", "status": "passed", "steps": [{"name": "Track a clearly non-existent order number", "status": "passed", "start": 1758377239548, "stop": 1758377239646}], "start": 1758377239547, "stop": 1758377239647, "uuid": "ffbd20e2-8f20-43ba-a2f7-07395f2d480c", "historyId": "d25dbd2a3564b1482fc3daed550acbca", "testCaseId": "d25dbd2a3564b1482fc3daed550acbca", "fullName": "tests.test_get_order_by_number#test_track_order_with_nonexistent_number_returns_error", "labels": [{"name": "feature", "value": "Orders"}, {"name": "story", "value": "Track order by number"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_number"}, {"name": "host", "value": "MacBook-Air.local"}, {"name": "thread", "value": "74856-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_number"}]}