{"name": "Tracking without number returns client error", "status": "passed", "steps": [{"name": "Call track endpoint without 't' parameter", "status": "passed", "start": 1758377239463, "stop": 1758377239545}], "start": 1758377239463, "stop": 1758377239545, "uuid": "8bc2885b-f5cf-4c9e-972b-640e5dc2a8f6", "historyId": "25874ca2e892805572faa4cb81593481", "testCaseId": "25874ca2e892805572faa4cb81593481", "fullName": "tests.test_get_order_by_number#test_track_order_without_number_returns_error", "labels": [{"name": "feature", "value": "Orders"}, {"name": "story", "value": "Track order by number"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_get_order_by_number"}, {"name": "host", "value": "MacBook-Air.local"}, {"name": "thread", "value": "74856-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_order_by_number"}]}